cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'gradle'
brew 'imagemagick'
brew 'node'
brew 'redis'
brew 'swiftlint'
brew 'go'
brew 'pyenv'
brew 'pyenv-virtualenv'

cask 'adium'
cask 'google-chrome'
cask 'dockertoolbox'
cask 'imageoptim'
cask 'postgres'
cask 'sublime-text3'
