cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'gradle'
brew 'imagemagick'
brew 'node'
brew 'redis'
brew 'swiftlint'
brew 'go'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'elixir'

cask 'adium'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'heroku-toolbelt'
cask 'imageoptim'
cask 'iterm2'
cask 'polymail'
cask 'postgres'
cask 'spotify'
cask 'sublime-text'
cask 'vlc'
